<?
	define('WP_ACCESS_LEVEL_INACTIVE',0);
	define('WP_ACCESS_LEVEL_STUDENT',1);
	define('WP_ACCESS_LEVEL_TEACHER',2);
	
	define('DRUPAL_ROLE_AUTHENTICATED',2);
	define('DRUPAL_ROLE_SUBSCRIBER',6);
	define('DRUPAL_ROLE_INACTIVE_STUDENT',7);
	define('DRUPAL_ROLE_TEACHER',4);
	
	# LIVE SITE VALUES
	# define('DRUPAL_ROLE_AUTHENTICATED',2);
	# define('DRUPAL_ROLE_SUBSCRIBER',7);
	# define('DRUPAL_ROLE_INACTIVE_STUDENT',8);
	# define('DRUPAL_ROLE_TEACHER',6);
?>